// Code generated by "stringer -type cmd command.go"; DO NOT EDIT

package bp35a1

import "fmt"

const _cmd_name = "SKSREGSKINFOSKSTARTSKJOINSKREJOINSKTERMSKSENDTOSKCONNECTSKSENDSKCLOSESKPINGSKSCANSKREGDEVSKRMDEVSKSETKEYSKRMKEYSKSECENABLESKSETPSKSKSETPWDSKSETRBIDSKADDNBRSKUDPPORTSKTCPPORTSKSAVESKLOADSKERASESKVERSKAPPVERSKRESETSKTABLESKDSLEEPSKRFLOSKLL64"

var _cmd_index = [...]uint8{0, 6, 12, 19, 25, 33, 39, 47, 56, 62, 69, 75, 81, 89, 96, 104, 111, 122, 130, 138, 147, 155, 164, 173, 179, 185, 192, 197, 205, 212, 219, 227, 233, 239}

func (i cmd) String() string {
	if i < 0 || i >= cmd(len(_cmd_index)-1) {
		return fmt.Sprintf("cmd(%d)", i)
	}
	return _cmd_name[_cmd_index[i]:_cmd_index[i+1]]
}
