// Code generated by "stringer -type ev event.go"; DO NOT EDIT

package bp35a1

import "fmt"

const _ev_name = "ESREGEINFOEVEREAPPVERERXUDPERXTCPEPONGETCPEADDRENEIGHBOREPANDESCEEDSCANEPORTEHANDLEEVENT"

var _ev_index = [...]uint8{0, 5, 10, 14, 21, 27, 33, 38, 42, 47, 56, 64, 71, 76, 83, 88}

func (i ev) String() string {
	if i < 0 || i >= ev(len(_ev_index)-1) {
		return fmt.Sprintf("ev(%d)", i)
	}
	return _ev_name[_ev_index[i]:_ev_index[i+1]]
}

func toEv(s string) ev {
	for i, _ := range _ev_index {
		if s == _ev_name[_ev_index[i]:_ev_index[i+1]] {
			return ev(i)
		}
	}
	return -1
}
